-- assert(solo.KeyCode.A ~= nil)
-- assert(solo.KeyCode.B ~= nil)
-- assert(solo.KeyCode.C ~= nil)
-- assert(solo.KeyCode.D ~= nil)
-- assert(solo.KeyCode.E ~= nil)
-- assert(solo.KeyCode.F ~= nil)
-- assert(solo.KeyCode.G ~= nil)
-- assert(solo.KeyCode.H ~= nil)
-- assert(solo.KeyCode.I ~= nil)
-- assert(solo.KeyCode.J ~= nil)
-- assert(solo.KeyCode.K ~= nil)
-- assert(solo.KeyCode.L ~= nil)
-- assert(solo.KeyCode.M ~= nil)
-- assert(solo.KeyCode.N ~= nil)
-- assert(solo.KeyCode.O ~= nil)
-- assert(solo.KeyCode.P ~= nil)
-- assert(solo.KeyCode.Q ~= nil)
-- assert(solo.KeyCode.R ~= nil)
-- assert(solo.KeyCode.S ~= nil)
-- assert(solo.KeyCode.T ~= nil)
-- assert(solo.KeyCode.U ~= nil)
-- assert(solo.KeyCode.V ~= nil)
-- assert(solo.KeyCode.W ~= nil)
-- assert(solo.KeyCode.X ~= nil)
-- assert(solo.KeyCode.Y ~= nil)
-- assert(solo.KeyCode.Z ~= nil)
-- assert(solo.KeyCode.LeftArrow ~= nil)
-- assert(solo.KeyCode.RightArrow ~= nil)
-- assert(solo.KeyCode.UpArrow ~= nil)
-- assert(solo.KeyCode.DownArrow ~= nil)
-- assert(solo.KeyCode.Escape ~= nil)
-- assert(solo.KeyCode.Space ~= nil)
-- assert(solo.KeyCode.Backspace ~= nil)

-- assert(solo.MouseButton.Left ~= nil)
-- assert(solo.MouseButton.Middle ~= nil)
-- assert(solo.MouseButton.Right ~= nil)

-- assert(solo.DeviceMode.Stub ~= nil)
-- assert(solo.DeviceMode.OpenGL ~= nil)

assert(solo.FaceCull.All ~= nil)
assert(solo.FaceCull.CCW ~= nil)
assert(solo.FaceCull.CW ~= nil)

assert(solo.MaterialParameterType.Float ~= nil)
assert(solo.MaterialParameterType.FloatArray ~= nil)
assert(solo.MaterialParameterType.Vector2 ~= nil)
assert(solo.MaterialParameterType.Vector2Array ~= nil)
assert(solo.MaterialParameterType.Vector3 ~= nil)
assert(solo.MaterialParameterType.Vector3Array ~= nil)
assert(solo.MaterialParameterType.Vector4 ~= nil)
assert(solo.MaterialParameterType.Vector4Array ~= nil)
assert(solo.MaterialParameterType.Matrix ~= nil)
assert(solo.MaterialParameterType.MatrixArray ~= nil)
assert(solo.MaterialParameterType.Texture ~= nil)
assert(solo.MaterialParameterType.CameraWorldPosition ~= nil)
assert(solo.MaterialParameterType.InverseTransposedWorldMatrix ~= nil)
assert(solo.MaterialParameterType.InverseTransposedWorldViewMatrix ~= nil)
assert(solo.MaterialParameterType.ProjectionMatrix ~= nil)
assert(solo.MaterialParameterType.ViewMatrix ~= nil)
assert(solo.MaterialParameterType.ViewProjectionMatrix ~= nil)
assert(solo.MaterialParameterType.WorldMatrix ~= nil)
assert(solo.MaterialParameterType.WorldViewMatrix ~= nil)
assert(solo.MaterialParameterType.WorldViewProjectionMatrix ~= nil)

assert(solo.TransformSpace.Self ~= nil)
assert(solo.TransformSpace.Parent ~= nil)
assert(solo.TransformSpace.World ~= nil)

assert(solo.TextureFiltering.Linear ~= nil)
assert(solo.TextureFiltering.Nearest ~= nil)
assert(solo.TextureFiltering.LinearMipmapLinear ~= nil)
assert(solo.TextureFiltering.LinearMipmapNearest ~= nil)
assert(solo.TextureFiltering.NearestMipmapLinear ~= nil)
assert(solo.TextureFiltering.NearestMipmapNearest ~= nil)

assert(solo.TextureFormat.Red ~= nil)
assert(solo.TextureFormat.Alpha ~= nil)
assert(solo.TextureFormat.RGB ~= nil)
assert(solo.TextureFormat.RGBA ~= nil)

assert(solo.TextureWrapping.Clamp ~= nil)
assert(solo.TextureWrapping.Repeat ~= nil)

assert(solo.PlaneIntersection.Front ~= nil)
assert(solo.PlaneIntersection.Back ~= nil)
assert(solo.PlaneIntersection.Intersecting ~= nil)

assert(solo.CubeTextureFace.Front ~= nil)
assert(solo.CubeTextureFace.Back ~= nil)
assert(solo.CubeTextureFace.Left ~= nil)
assert(solo.CubeTextureFace.Right ~= nil)
assert(solo.CubeTextureFace.Top ~= nil)
assert(solo.CubeTextureFace.Bottom ~= nil)

assert(solo.DepthFunction.Never ~= nil)
assert(solo.DepthFunction.Less ~= nil)
assert(solo.DepthFunction.Equal ~= nil)
assert(solo.DepthFunction.LEqual ~= nil)
assert(solo.DepthFunction.Greater ~= nil)
assert(solo.DepthFunction.NotEqual ~= nil)
assert(solo.DepthFunction.GEqual ~= nil)
assert(solo.DepthFunction.Always ~= nil)

-- assert(solo.PrimitiveType.Lines ~= nil)
-- assert(solo.PrimitiveType.LineStrip ~= nil)
-- assert(solo.PrimitiveType.Points ~= nil)
-- assert(solo.PrimitiveType.TriangleStrip ~= nil)
-- assert(solo.PrimitiveType.Triangles ~= nil)

-- assert(solo.VertexBufferLayoutSemantics.Position ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.Normal ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.Color ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.Tangent ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.Binormal ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord0 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord1 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord2 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord3 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord4 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord5 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord6 ~= nil)
-- assert(solo.VertexBufferLayoutSemantics.TexCoord7 ~= nil)

-- assert(solo.MeshPrefab.Quad ~= nil)
-- assert(solo.MeshPrefab.Cube ~= nil)

assert(solo.EffectPrefab.Skybox ~= nil)
assert(solo.EffectPrefab.Font ~= nil)

assert(solo.BlendFactor.Zero ~= nil)
assert(solo.BlendFactor.One ~= nil)
assert(solo.BlendFactor.SrcColor ~= nil)
assert(solo.BlendFactor.OneMinusSrcColor ~= nil)
assert(solo.BlendFactor.DstColor ~= nil)
assert(solo.BlendFactor.OneMinusDstColor ~= nil)
assert(solo.BlendFactor.SrcAlpha ~= nil)
assert(solo.BlendFactor.OneMinusSrcAlpha ~= nil)
assert(solo.BlendFactor.DstAlpha ~= nil)
assert(solo.BlendFactor.OneMinusDstAlpha ~= nil)
assert(solo.BlendFactor.ConstantAlpha ~= nil)
assert(solo.BlendFactor.OneMinusConstantAlpha ~= nil)
assert(solo.BlendFactor.SrcAlphaSaturate ~= nil)

assert(solo.PolygonMode.Points ~= nil)
assert(solo.PolygonMode.Triangle ~= nil)
assert(solo.PolygonMode.Wireframe ~= nil)
