/* 
 * Copyright (c) Aleksey Fedotov 
 * MIT license 
 */

#pragma once

#include "SoloEnums.h"
#include "SoloAsyncHandle.h"
#include "SoloBoxCollider.h"
#include "SoloCamera.h"
#include "SoloCollider.h"
#include "SoloCommon.h"
#include "SoloComponent.h"
#include "math/SoloDegrees.h"
#include "SoloDevice.h"
#include "SoloDeviceSetup.h"
#include "SoloEffect.h"
#include "SoloFileSystem.h"
#include "SoloFont.h"
#include "SoloFontMesh.h"
#include "SoloFormatter.h"
#include "SoloFrameBuffer.h"
#include "SoloHash.h"
#include "SoloJobPool.h"
#include "SoloMaterial.h"
#include "math/SoloMath.h"
#include "math/SoloMatrix.h"
#include "SoloMesh.h"
#include "SoloMeshRenderer.h"
#include "SoloNode.h"
#include "SoloPhysics.h"
#include "math/SoloQuaternion.h"
#include "math/SoloRadians.h"
#include "math/SoloRay.h"
#include "SoloRenderer.h"
#include "SoloRigidBody.h"
#include "SoloScene.h"
#include "SoloScriptRuntime.h"
#include "SoloSpectator.h"
#include "SoloSpinLock.h"
#include "SoloStaticMeshCollider.h"
#include "SoloStringUtils.h"
#include "SoloTexture.h"
#include "SoloTextureData.h"
#include "SoloTransform.h"
#include "math/SoloVector2.h"
#include "math/SoloVector3.h"
#include "math/SoloVector4.h"
#include "SoloVertexBufferLayout.h"