assert(sl.TransformSpace.Parent ~= nil)
assert(sl.TransformSpace.Self ~= nil)
assert(sl.TransformSpace.World ~= nil)

assert(sl.TextureWrap.ClampToEdge ~= nil)
assert(sl.TextureWrap.ClampToBorder ~= nil)
assert(sl.TextureWrap.Repeat ~= nil)
assert(sl.TextureWrap.MirrorRepeat ~= nil)

assert(sl.TextureFormat.RGB8 ~= nil)
assert(sl.TextureFormat.RGBA8 ~= nil)
assert(sl.TextureFormat.RGBA16F ~= nil)
assert(sl.TextureFormat.R8 ~= nil)
assert(sl.TextureFormat.Depth24 ~= nil)

assert(sl.TextureFilter.Nearest ~= nil)
assert(sl.TextureFilter.Linear ~= nil)

assert(sl.TextureMipFilter.Nearest ~= nil)
assert(sl.TextureMipFilter.Linear ~= nil)
assert(sl.TextureMipFilter.None ~= nil)

assert(sl.MaterialPrefab.Font ~= nil)

assert(sl.FaceCull.None ~= nil)
assert(sl.FaceCull.Front ~= nil)
assert(sl.FaceCull.Back ~= nil)

assert(sl.PolygonMode.Points ~= nil)
assert(sl.PolygonMode.Fill ~= nil)
assert(sl.PolygonMode.Wireframe ~= nil)

assert(sl.DepthFunction.Never ~= nil)
assert(sl.DepthFunction.Always ~= nil)
assert(sl.DepthFunction.Equal ~= nil)
assert(sl.DepthFunction.NotEqual ~= nil)
assert(sl.DepthFunction.Less ~= nil)
assert(sl.DepthFunction.LEqual ~= nil)
assert(sl.DepthFunction.Greater ~= nil)
assert(sl.DepthFunction.GEqual ~= nil)

assert(sl.BlendFactor.Zero ~= nil)
assert(sl.BlendFactor.One ~= nil)
assert(sl.BlendFactor.SrcColor ~= nil)
assert(sl.BlendFactor.OneMinusSrcColor ~= nil)
assert(sl.BlendFactor.DstColor ~= nil)
assert(sl.BlendFactor.OneMinusDstColor ~= nil)
assert(sl.BlendFactor.SrcAlpha ~= nil)
assert(sl.BlendFactor.OneMinusSrcAlpha ~= nil)
assert(sl.BlendFactor.DstAlpha ~= nil)
assert(sl.BlendFactor.OneMinusDstAlpha ~= nil)
assert(sl.BlendFactor.ConstantAlpha ~= nil)
assert(sl.BlendFactor.OneMinusConstantAlpha ~= nil)
assert(sl.BlendFactor.SrcAlphaSaturate ~= nil)

assert(sl.BindParameterSemantics.WorldMatrix ~= nil)
assert(sl.BindParameterSemantics.ViewMatrix ~= nil)
assert(sl.BindParameterSemantics.ProjectionMatrix ~= nil)
assert(sl.BindParameterSemantics.WorldViewMatrix ~= nil)
assert(sl.BindParameterSemantics.ViewProjectionMatrix ~= nil)
assert(sl.BindParameterSemantics.WorldViewProjectionMatrix ~= nil)
assert(sl.BindParameterSemantics.InverseTransposedWorldMatrix ~= nil)
assert(sl.BindParameterSemantics.InverseTransposedWorldViewMatrix ~= nil)
assert(sl.BindParameterSemantics.CameraWorldPosition ~= nil)

assert(sl.KeyCode.Digit0 ~= nil)
assert(sl.KeyCode.Digit1 ~= nil)
assert(sl.KeyCode.Digit2 ~= nil)
assert(sl.KeyCode.Digit3 ~= nil)
assert(sl.KeyCode.Digit4 ~= nil)
assert(sl.KeyCode.Digit5 ~= nil)
assert(sl.KeyCode.Digit6 ~= nil)
assert(sl.KeyCode.Digit7 ~= nil)
assert(sl.KeyCode.Digit8 ~= nil)
assert(sl.KeyCode.Digit9 ~= nil)
assert(sl.KeyCode.A ~= nil)
assert(sl.KeyCode.B ~= nil)
assert(sl.KeyCode.C ~= nil)
assert(sl.KeyCode.D ~= nil)
assert(sl.KeyCode.E ~= nil)
assert(sl.KeyCode.F ~= nil)
assert(sl.KeyCode.G ~= nil)
assert(sl.KeyCode.H ~= nil)
assert(sl.KeyCode.I ~= nil)
assert(sl.KeyCode.J ~= nil)
assert(sl.KeyCode.K ~= nil)
assert(sl.KeyCode.L ~= nil)
assert(sl.KeyCode.M ~= nil)
assert(sl.KeyCode.N ~= nil)
assert(sl.KeyCode.O ~= nil)
assert(sl.KeyCode.P ~= nil)
assert(sl.KeyCode.Q ~= nil)
assert(sl.KeyCode.R ~= nil)
assert(sl.KeyCode.S ~= nil)
assert(sl.KeyCode.T ~= nil)
assert(sl.KeyCode.U ~= nil)
assert(sl.KeyCode.V ~= nil)
assert(sl.KeyCode.W ~= nil)
assert(sl.KeyCode.X ~= nil)
assert(sl.KeyCode.Y ~= nil)
assert(sl.KeyCode.Z ~= nil)
assert(sl.KeyCode.LeftArrow ~= nil)
assert(sl.KeyCode.RightArrow ~= nil)
assert(sl.KeyCode.UpArrow ~= nil)
assert(sl.KeyCode.DownArrow ~= nil)
assert(sl.KeyCode.Escape ~= nil)
assert(sl.KeyCode.Backspace ~= nil)
assert(sl.KeyCode.Space ~= nil)
assert(sl.KeyCode.Return ~= nil)
assert(sl.KeyCode.LeftShift ~= nil)
assert(sl.KeyCode.LeftCtrl ~= nil)
assert(sl.KeyCode.LeftAlt ~= nil)
assert(sl.KeyCode.RightShift ~= nil)
assert(sl.KeyCode.RightCtrl ~= nil)
assert(sl.KeyCode.RightAlt ~= nil)

assert(sl.MouseButton.Left ~= nil)
assert(sl.MouseButton.Middle ~= nil)
assert(sl.MouseButton.Right ~= nil)

assert(sl.DeviceMode.Null ~= nil)
assert(sl.DeviceMode.OpenGL ~= nil)
assert(sl.DeviceMode.Vulkan ~= nil)

assert(sl.MeshPrefab.Cube ~= nil)
assert(sl.MeshPrefab.Quad ~= nil)

assert(sl.PrimitiveType.Triangles ~= nil)
assert(sl.PrimitiveType.TriangleStrip ~= nil)
assert(sl.PrimitiveType.Lines ~= nil)
assert(sl.PrimitiveType.LineStrip ~= nil)
assert(sl.PrimitiveType.Points ~= nil)

assert(sl.VertexAttributeSemantics.Position ~= nil)
assert(sl.VertexAttributeSemantics.Normal ~= nil)
assert(sl.VertexAttributeSemantics.TexCoord ~= nil)
assert(sl.VertexAttributeSemantics.Tangent ~= nil)
assert(sl.VertexAttributeSemantics.Binormal ~= nil)