local scene = sl.Scene.empty(sl.device)
local node = scene:createNode()

local cam = node:addComponent('Camera')
cam:update()
cam:render()
assert(cam:typeId())
assert(cam:node() == node)
assert(cam:tag())
cam:setTag(123)
assert(cam:enabled())
cam:setEnabled(false)