assert(sl.TransformSpace.Parent)
assert(sl.TransformSpace.Self)
assert(sl.TransformSpace.World)

assert(sl.TextureWrap.ClampToEdge)
assert(sl.TextureWrap.ClampToBorder)
assert(sl.TextureWrap.Repeat)
assert(sl.TextureWrap.MirrorRepeat)

assert(sl.TextureFormat.RGB8)
assert(sl.TextureFormat.RGBA8)
assert(sl.TextureFormat.RGBA16F)
assert(sl.TextureFormat.R8)
assert(sl.TextureFormat.Depth24)

assert(sl.TextureFilter.Nearest)
assert(sl.TextureFilter.Linear)

assert(sl.TextureMipFilter.Nearest)
assert(sl.TextureMipFilter.Linear)
assert(sl.TextureMipFilter.None)

assert(sl.FaceCull.None)
assert(sl.FaceCull.Back)
assert(sl.FaceCull.Front)

assert(sl.PolygonMode.Points)
assert(sl.PolygonMode.Fill)
assert(sl.PolygonMode.Wireframe)

assert(sl.DepthFunction.Never)
assert(sl.DepthFunction.Always)
assert(sl.DepthFunction.Equal)
assert(sl.DepthFunction.NotEqual)
assert(sl.DepthFunction.Less)
assert(sl.DepthFunction.LEqual)
assert(sl.DepthFunction.Greater)
assert(sl.DepthFunction.GEqual)

assert(sl.BlendFactor.Zero)
assert(sl.BlendFactor.One)
assert(sl.BlendFactor.SrcColor)
assert(sl.BlendFactor.OneMinusSrcColor)
assert(sl.BlendFactor.DstColor)
assert(sl.BlendFactor.OneMinusDstColor)
assert(sl.BlendFactor.SrcAlpha)
assert(sl.BlendFactor.OneMinusSrcAlpha)
assert(sl.BlendFactor.DstAlpha)
assert(sl.BlendFactor.OneMinusDstAlpha)
assert(sl.BlendFactor.ConstantAlpha)
assert(sl.BlendFactor.OneMinusConstantAlpha)
assert(sl.BlendFactor.SrcAlphaSaturate)

assert(sl.ParameterBinding.WorldMatrix)
assert(sl.ParameterBinding.ViewMatrix)
assert(sl.ParameterBinding.ProjectionMatrix)
assert(sl.ParameterBinding.WorldViewMatrix)
assert(sl.ParameterBinding.ViewProjectionMatrix)
assert(sl.ParameterBinding.WorldViewProjectionMatrix)
assert(sl.ParameterBinding.InverseTransposedWorldMatrix)
assert(sl.ParameterBinding.InverseTransposedWorldViewMatrix)
assert(sl.ParameterBinding.CameraWorldPosition)

assert(sl.KeyCode.Digit0)
assert(sl.KeyCode.Digit1)
assert(sl.KeyCode.Digit2)
assert(sl.KeyCode.Digit3)
assert(sl.KeyCode.Digit4)
assert(sl.KeyCode.Digit5)
assert(sl.KeyCode.Digit6)
assert(sl.KeyCode.Digit7)
assert(sl.KeyCode.Digit8)
assert(sl.KeyCode.Digit9)
assert(sl.KeyCode.A)
assert(sl.KeyCode.B)
assert(sl.KeyCode.C)
assert(sl.KeyCode.D)
assert(sl.KeyCode.E)
assert(sl.KeyCode.F)
assert(sl.KeyCode.G)
assert(sl.KeyCode.H)
assert(sl.KeyCode.I)
assert(sl.KeyCode.J)
assert(sl.KeyCode.K)
assert(sl.KeyCode.L)
assert(sl.KeyCode.M)
assert(sl.KeyCode.N)
assert(sl.KeyCode.O)
assert(sl.KeyCode.P)
assert(sl.KeyCode.Q)
assert(sl.KeyCode.R)
assert(sl.KeyCode.S)
assert(sl.KeyCode.T)
assert(sl.KeyCode.U)
assert(sl.KeyCode.V)
assert(sl.KeyCode.W)
assert(sl.KeyCode.X)
assert(sl.KeyCode.Y)
assert(sl.KeyCode.Z)
assert(sl.KeyCode.LeftArrow)
assert(sl.KeyCode.RightArrow)
assert(sl.KeyCode.UpArrow)
assert(sl.KeyCode.DownArrow)
assert(sl.KeyCode.Escape)
assert(sl.KeyCode.Backspace)
assert(sl.KeyCode.Space)
assert(sl.KeyCode.Return)
assert(sl.KeyCode.LeftShift)
assert(sl.KeyCode.LeftCtrl)
assert(sl.KeyCode.LeftAlt)
assert(sl.KeyCode.RightShift)
assert(sl.KeyCode.RightCtrl)
assert(sl.KeyCode.RightAlt)

assert(sl.MouseButton.Left)
assert(sl.MouseButton.Middle)
assert(sl.MouseButton.Right)

assert(sl.DeviceMode.OpenGL)
assert(sl.DeviceMode.Vulkan)

assert(sl.PrimitiveType.Triangles)
assert(sl.PrimitiveType.TriangleStrip)
assert(sl.PrimitiveType.Lines)
assert(sl.PrimitiveType.LineStrip)
assert(sl.PrimitiveType.Points)

assert(sl.VertexAttributeUsage.Position)
assert(sl.VertexAttributeUsage.Normal)
assert(sl.VertexAttributeUsage.TexCoord)
assert(sl.VertexAttributeUsage.Tangent)
assert(sl.VertexAttributeUsage.Binormal)

assert(sl.IndexElementSize.Bits16)
assert(sl.IndexElementSize.Bits32)
