runTest(function()
	local flags = solo.BitFlags()
	flags:clear()
	flags:add(1)
	assert(flags:checkAndRemove(1) == true)
	flags:getRaw()
	assert(flags:isEmpty() == true)
	flags:isSet(1)
	flags:remove(1)
	flags:set(1)
end, "BitFlags")
