runTest(function()
	local args = solo.DeviceCreationArgs()
	assert(args.mode ~= nil)
	assert(args.bits > 0)
	assert(args.canvasWidth > 0)
	assert(args.canvasHeight > 0)
	assert(args.depth > 0)
	assert(args.fullScreen ~= nil)
	assert(args.windowTitle ~= nil)
	assert(args.logFilePath ~= nil)

	assert(device:getScene())
	assert(device:getResourceManager())
	assert(device:getFileSystem())
	assert(device:getGraphics())
	assert(device:getMode() ~= nil)
	device:stopRunning()
	-- device:shutdown() not called deliberately

	device:setWindowTitle("Some title")
	assert(device:getWindowTitle() == "Some title")
	device:setCursorCaptured()
	assert(device:getCanvasSize() ~= nil)
	assert(device:getLifetime() ~= nil)
	assert(device:isKeyPressed(solo.KeyCode.A) ~= nil)
	assert(device:isKeyReleased(solo.KeyCode.A) ~= nil)
	assert(device:getMouseMotion())
	assert(device:isMouseButtonDown(solo.MouseButton.Left) ~= nil)
	assert(device:isMouseButtonReleased(solo.MouseButton.Left) ~= nil)
	assert(device:getTimeDelta() ~= nil)

	device:saveScreenshot("abc")
end, "Device")
