runTest(function()
	assert(solo.DeviceCreationArgs())
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2, true))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2, true, "Test title"))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2, true, "Test title", 3))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2, true, "Test title", 3, 4))
	assert(solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2, true, "Test title", 3, 4, "log.file"))

	local args = solo.DeviceCreationArgs(solo.DeviceMode.OpenGL, 1, 2, true, "Test title", 3, 4, "log.file")
	assert(args.mode == solo.DeviceMode.OpenGL)
	assert(args.bits == 3)
	assert(args.canvasWidth == 1)
	assert(args.canvasHeight == 2)
	assert(args.depth == 4)
	assert(args.fullScreen == true)
	assert(args.windowTitle == "Test title")

	assert(device:getScene())
	assert(device:getResourceManager())
	assert(device:getFileSystem())
	assert(device:getGraphics())
	assert(device:getMode() ~= nil)
	device:requestShutdown()
	assert(device:shutdownRequested() ~= nil)

	device:setWindowTitle("Some title")
	assert(device:getWindowTitle() == "Some title")
	device:setCursorCaptured()
	assert(device:getCanvasSize() ~= nil)
	assert(device:getLifetime() ~= nil)
	assert(device:isKeyPressed(solo.KeyCode.A) ~= nil)
	assert(device:isKeyReleased(solo.KeyCode.A) ~= nil)
	assert(device:getMouseMotion())
	assert(device:isMouseButtonDown(solo.MouseButton.Left) ~= nil)
	assert(device:isMouseButtonReleased(solo.MouseButton.Left) ~= nil)
	assert(device:getTimeDelta() ~= nil)
end, "Device")
