runTest(function()
	local f = solo.Frustum()
	local v = solo.Vector3(1, 2, 3)
	assert(f:getNearPlane())
	assert(f:getFarPlane())
	assert(f:getLeftPlane())
	assert(f:getRightPlane())
	assert(f:getTopPlane())
	assert(f:getBottomPlane())
	assert(f:getMatrix())
	f:setMatrix(solo.Matrix())
	assert(f:getCorners())
	assert(f:getNearCorners())
	assert(f:getFarCorners())
	assert(f:intersectsPoint(v) ~= nil)
	assert(f:intersectsRay(solo.Ray(v, v)) ~= nil)
	assert(f:intersectsBoundingBox(solo.BoundingBox(v, v)) ~= nil)
	assert(f:intersectsBoundingSphere(solo.BoundingSphere(v, 1)) ~= nil)
	assert(f:getPlaneIntersection(solo.Plane(v, 1)) ~= nil)
end, "Frustum")
