runTest(function()
	local p = solo.Plane(solo.Vector3(1, 2, 3), 1)
	local v = solo.Vector3(1, 2, 3)
	assert(solo.Plane.getCommonPoint(p, p, p))
	assert(p:getNormal())
	p:setNormal(solo.Vector3(1, 2, 3))
	assert(p:getDistance() ~= nil)
	p:setDistance(1)
	assert(p:getDistanceToPoint(solo.Vector3(1, 2, 3)) ~= nil)
	assert(p:isParallel(p) ~= nil)
	p:transform(solo.Matrix())
end, "Plane")
