/*
    Copyright (c) Aleksey Fedotov
    MIT license
*/

#pragma once

#include "SoloAssetLoader.h"
#include "SoloBoundingBox.h"
#include "SoloBoundingSphere.h"
#include "SoloBoxCollider.h"
#include "SoloCamera.h"
#include "SoloCollider.h"
#include "SoloCommon.h"
#include "SoloComponent.h"
#include "SoloCubeTexture.h"
#include "SoloDegree.h"
#include "SoloDevice.h"
#include "SoloDeviceSetup.h"
#include "SoloEffect.h"
#include "SoloFileSystem.h"
#include "SoloFont.h"
#include "SoloFontRenderer.h"
#include "SoloFormatter.h"
#include "SoloFrameBuffer.h"
#include "SoloFrustum.h"
#include "SoloImage.h"
#include "SoloLogger.h"
#include "SoloMaterial.h"
#include "SoloMath.h"
#include "SoloMatrix.h"
#include "SoloMesh.h"
#include "SoloMeshRenderer.h"
#include "SoloNode.h"
#include "SoloPhysics.h"
#include "SoloPlane.h"
#include "SoloQuaternion.h"
#include "SoloRadian.h"
#include "SoloRay.h"
#include "SoloRectTexture.h"
#include "SoloRenderer.h"
#include "SoloRigidBody.h"
#include "SoloScene.h"
#include "SoloScriptRuntime.h"
#include "SoloSkyboxRenderer.h"
#include "SoloSpectator.h"
#include "SoloTexture.h"
#include "SoloTransform.h"
#include "SoloTransformMatrix.h"
#include "SoloVector2.h"
#include "SoloVector3.h"
#include "SoloVector4.h"
#include "SoloVertexFormat.h"
