runTest(function()
	local mgr = device:getResourceManager()
	local e = mgr:getOrCreateEffect("vs", "fs")
	local v2 = solo.Vector2.unit()
	local v3 = solo.Vector3.unit()
	local v4 = solo.Vector4.unit()
	local m = solo.Matrix()
	local tex = mgr:getOrCreateTexture2D()
end, "Effect")
