runTest(function()
	local rmgr = device:getResourceManager()
	local e = rmgr:getOrCreateEffect("vs", "fs")
	local m = rmgr:getOrCreateMaterial(e, "test/uri")
	local fb = rmgr:getOrCreateFrameBuffer("test")
	local renderer = rmgr:getOrCreateSurfaceRenderer(m)
	renderer:renderSurface(fb)
	renderer:renderSurface(nil)
	renderer:renderSurface()
end, "SurfaceRenderer")
