runTest(function()
	local rmgr = device:getResourceManager()
	local e = rmgr:getOrCreateEffect("vs", "fs")
	local m = rmgr:getOrCreateMaterial(e, "test/uri")
	local fb = rmgr:getOrCreateFrameBuffer("test")
	local g = device:getGraphics()
	g:blit(m, fb)
	g:blit(m, nil)
	g:blit(m)
end, "Graphics")
