runTest(function()
	local device = engine:getDevice()
	assert(device)
	device:setWindowTitle("Some title")
	assert(device:getWindowTitle() == "Some title")
	device:setCursorCaptured()
	assert(device:getCanvasSize() ~= nil)
	assert(device:getLifetime() ~= nil)
	assert(device:isKeyPressed(solo.KeyCode_A) ~= nil)
	assert(device:isKeyReleased(solo.KeyCode_A) ~= nil)
	assert(device:getMouseMotion())
	assert(device:isMouseButtonDown(solo.MouseButton_Left) ~= nil)
	assert(device:isMouseButtonReleased(solo.MouseButton_Left) ~= nil)
	assert(device:getTimeDelta() ~= nil)
end, "Device")
