runTest(function()
	local v1 = solo.Vector3(1, 2, 3)
	local v2 = solo.Vector3(2, 3, 4)
	assert(solo.Vector3.zero())
	assert(solo.Vector3.unit())
	assert(solo.Vector3.unitX())
	assert(solo.Vector3.unitY())
	assert(solo.Vector3.unitZ())
	assert(solo.Vector3.angle(v1, v2))
	assert(solo.Vector3.cross(v1, v2))
	assert(solo.Vector3.dot(v1, v2))
	assert(v1:dot(v2) ~= nil)
	assert(v1:distance(v2) ~= nil)
	assert(v1:distanceSquared(v2) ~= nil)
	v1:clamp(v1, v2)
	assert(v1:length() ~= nil)
	assert(v1:lengthSquared() ~= nil)
	assert(v1:isUnit() ~= nil)
	assert(v1:isZero() ~= nil)
	v1:normalize()
	assert(v1:normalized())
	assert(v1:plusScalar(1):addScalar(2):plusVector3(v1):addVector3(v1))
	assert(v1:productScalar(1):multScalar(1))
	assert(v1.x)
	assert(v1.y)
	assert(v1.z)
end, "Vector3")
