runTest(function()
	local mgr = engine:getResourceManager()
	local t = mgr:getOrCreateCubeTexture()
	t:setData(solo.CubeTextureFace_Front, solo.ColorFormat_RGB, {1, 2, 3, 4}, 2, 2)
	t:generateMipmaps()
	assert(t:getVerticalWrapping() ~= nil)
	assert(t:getHorizontalWrapping() ~= nil)
	assert(t:getDepthWrapping() ~= nil)
	assert(t:getMinFiltering() ~= nil)
	assert(t:getMagFiltering() ~= nil)
	assert(t:getAnisotropyLevel() ~= nil)
	t:setVerticalWrapping(solo.TextureWrapping_Clamp)
	t:setHorizontalWrapping(solo.TextureWrapping_Clamp)
	t:setDepthWrapping(solo.TextureWrapping_Clamp)
	t:setWrapping(solo.TextureWrapping_Clamp)
	t:setMinFiltering(solo.TextureFiltering_Linear)
	t:setMagFiltering(solo.TextureFiltering_Linear)
	t:setFiltering(solo.TextureFiltering_Linear)
	t:setAnisotropyLevel(1)
end, "CubeTexture")
