runTest(function()
	local g = device:getGraphics()
	local e = device:getResourceManager():getOrCreateEffect("vs", "fs")
	local m = device:getResourceManager():getOrCreateMaterial(e, "test/uri")
	local rt = device:getResourceManager():getOrCreateRenderTarget("test")
	g:renderMaterialSurfaceToTarget(m, rt)
	g:renderMaterialSurfaceToScreen(m)
end, "Graphics")
