runTest(function()
	local v1 = solo.Vector2(1, 2)
	local v2 = solo.Vector2(2, 3)
	assert(solo.Vector2.zero())
	assert(solo.Vector2.unit())
	assert(solo.Vector2.unitX())
	assert(solo.Vector2.unitY())
	assert(solo.Vector2.angle(v1, v2))
	assert(solo.Vector2.dot(v1, v2))
	assert(v1:dot(v2) ~= nil)
	assert(v1:distance(v2) ~= nil)
	assert(v1:distanceSquared(v2) ~= nil)
	v1:clamp(v1, v2)
	assert(v1:length() ~= nil)
	assert(v1:lengthSquared() ~= nil)
	assert(v1:isUnit() ~= nil)
	assert(v1:isZero() ~= nil)
	v1:normalize()
	assert(v1:normalized())
	assert(v1:plusScalar(1):addScalar(2):plusVector2(solo.Vector2.unit()):addVector2(solo.Vector2.unit()))
	assert(v1.x ~= nil)
	assert(v1.y ~= nil)
end, "Vector2")
