runTest(function()
	local mgr = engine:getResourceManager()
	local t = mgr:getOrCreateCubeTexture()
	t:setData(solo.CubeTextureFace_Front, solo.ColorFormat_RGB, {1, 2, 3, 4}, 2, 2)
	t:generateMipmaps()
	assert(t:getVerticalWrapMode() ~= nil)
	assert(t:getHorizontalWrapMode() ~= nil)
	assert(t:getDepthWrapMode() ~= nil)
	assert(t:getMinFilter() ~= nil)
	assert(t:getMagFilter() ~= nil)
	assert(t:getAnisotropyLevel() ~= nil)
	t:setVerticalWrapMode(solo.TextureWrapMode_Clamp)
	t:setHorizontalWrapMode(solo.TextureWrapMode_Clamp)
	t:setDepthWrapMode(solo.TextureWrapMode_Clamp)
	t:setMinFilter(solo.TextureFilter_Linear)
	t:setMagFilter(solo.TextureFilter_Linear)
	t:setAnisotropyLevel(1)
end, "CubeTexture")
