runTest(function()
	local scene = device:getScene()
	local s = scene:createNode():addComponent("Spectator")
	assert(s:getHorizontalRotationSpeed() ~= nil)
	assert(s:getVerticalRotationSpeed() ~= nil)
	assert(s:getMovementSpeed() ~= nil)
	s:setHorizontalRotationSpeed(1)
	s:setVerticalRotationSpeed(2)
	s:setMovementSpeed(3)
end, "Spectator")
