runTest(function()
	local mgr = device:getResourceManager()
	local e = mgr:getOrCreateEffect("vs", "fs")
	local v2 = solo.Vector2.unit()
	local v3 = solo.Vector3.unit()
	local v4 = solo.Vector4.unit()
	local m = solo.Matrix()
	local tex = mgr:getOrCreateTexture2D()

	local var = e:findVariable("wer")
	assert(var)
	var:setFloat(1)
	var:setFloatArray({1, 2, 3})
	var:setInt(1)
	var:setIntArray({1, 2, 3})
	var:setVector2(v2)
	var:setVector2Array({v2})
	var:setVector3(v3)
	var:setVector3Array({v3})
	var:setVector4(v4)
	var:setVector4Array({v4})
	var:setMatrix(m)
	var:setMatrixArray({m})
	var:setTexture(tex)
	var:setTextureArray({tex})
end, "Effect")
