runTest(function()
	local scene = device:getScene()
	local mgr = device:getResourceManager()
	local mr = scene:createNode():addComponent("ModelRenderer")
	local mesh = mgr:getOrCreateMesh("wer")
	local model = mgr:getOrCreateModel("model")
	model:addMesh(mesh)
	mr:setModel(model)
	assert(mr:getModel())
end, "ModelRenderer")
