runTest(function()
	assert(solo.KeyCode.A ~= nil)
	assert(solo.KeyCode.B ~= nil)
	assert(solo.KeyCode.C ~= nil)
	assert(solo.KeyCode.D ~= nil)
	assert(solo.KeyCode.E ~= nil)
	assert(solo.KeyCode.F ~= nil)
	assert(solo.KeyCode.G ~= nil)
	assert(solo.KeyCode.H ~= nil)
	assert(solo.KeyCode.I ~= nil)
	assert(solo.KeyCode.J ~= nil)
	assert(solo.KeyCode.K ~= nil)
	assert(solo.KeyCode.L ~= nil)
	assert(solo.KeyCode.M ~= nil)
	assert(solo.KeyCode.N ~= nil)
	assert(solo.KeyCode.O ~= nil)
	assert(solo.KeyCode.P ~= nil)
	assert(solo.KeyCode.Q ~= nil)
	assert(solo.KeyCode.R ~= nil)
	assert(solo.KeyCode.S ~= nil)
	assert(solo.KeyCode.T ~= nil)
	assert(solo.KeyCode.U ~= nil)
	assert(solo.KeyCode.V ~= nil)
	assert(solo.KeyCode.W ~= nil)
	assert(solo.KeyCode.X ~= nil)
	assert(solo.KeyCode.Y ~= nil)
	assert(solo.KeyCode.Z ~= nil)
	assert(solo.KeyCode.LeftArrow ~= nil)
	assert(solo.KeyCode.RightArrow ~= nil)
	assert(solo.KeyCode.UpArrow ~= nil)
	assert(solo.KeyCode.DownArrow ~= nil)
	assert(solo.KeyCode.Escape ~= nil)

	assert(solo.MouseButton.Left ~= nil)
	assert(solo.MouseButton.Middle ~= nil)
	assert(solo.MouseButton.Right ~= nil)

	assert(solo.DeviceMode.Stub ~= nil)
	assert(solo.DeviceMode.OpenGL ~= nil)

	assert(solo.PolygonFace.All ~= nil)
	assert(solo.PolygonFace.CCW ~= nil)
	assert(solo.PolygonFace.CW ~= nil)

	assert(solo.AutoBinding.CameraWorldPosition ~= nil)
	assert(solo.AutoBinding.InverseTransposedWorldMatrix ~= nil)
	assert(solo.AutoBinding.InverseTransposedWorldViewMatrix ~= nil)
	assert(solo.AutoBinding.ProjectionMatrix ~= nil)
	assert(solo.AutoBinding.ViewMatrix ~= nil)
	assert(solo.AutoBinding.ViewProjectionMatrix ~= nil)
	assert(solo.AutoBinding.WorldMatrix ~= nil)
	assert(solo.AutoBinding.WorldViewMatrix ~= nil)
	assert(solo.AutoBinding.WorldViewProjectionMatrix ~= nil)
	assert(solo.AutoBinding.None ~= nil)

	assert(solo.TransformSpace.Self ~= nil)
	assert(solo.TransformSpace.Parent ~= nil)
	assert(solo.TransformSpace.World ~= nil)

	assert(solo.TextureFiltering.Linear ~= nil)
	assert(solo.TextureFiltering.Nearest ~= nil)
	assert(solo.TextureFiltering.LinearMipmapLinear ~= nil)
	assert(solo.TextureFiltering.LinearMipmapNearest ~= nil)
	assert(solo.TextureFiltering.NearestMipmapLinear ~= nil)
	assert(solo.TextureFiltering.NearestMipmapNearest ~= nil)

	assert(solo.ColorFormat.RGB ~= nil)
	assert(solo.ColorFormat.RGBA ~= nil)

	assert(solo.TextureWrapping.Clamp ~= nil)
	assert(solo.TextureWrapping.Repeat ~= nil)

	assert(solo.PlaneIntersection.Front ~= nil)
	assert(solo.PlaneIntersection.Back ~= nil)
	assert(solo.PlaneIntersection.Intersecting ~= nil)

	assert(solo.CubeTextureFace.Front ~= nil)
	assert(solo.CubeTextureFace.Back ~= nil)
	assert(solo.CubeTextureFace.Left ~= nil)
	assert(solo.CubeTextureFace.Right ~= nil)
	assert(solo.CubeTextureFace.Top ~= nil)
	assert(solo.CubeTextureFace.Bottom ~= nil)

	assert(solo.DepthPassFunction.Never ~= nil)
	assert(solo.DepthPassFunction.Less ~= nil)
	assert(solo.DepthPassFunction.Equal ~= nil)
	assert(solo.DepthPassFunction.LEqual ~= nil)
	assert(solo.DepthPassFunction.Greater ~= nil)
	assert(solo.DepthPassFunction.NotEqual ~= nil)
	assert(solo.DepthPassFunction.GEqual ~= nil)
	assert(solo.DepthPassFunction.Always ~= nil)
end, "Enums")
