runTest(function()
	local mgr = engine:getResourceManager()
	mgr:findEffect("wer")
	mgr:findTexture("wer")
	mgr:findMaterial("wer")
	mgr:findMesh("wer")
	mgr:findModel("wer")
	mgr:findRenderTarget("wer")
	local ef = mgr:getOrCreateEffect("wer", "wer", "uri")
	assert(ef)
	assert(mgr:getOrCreateTexture2D("sdf"))
	assert(mgr:getOrCreateMaterial(ef, "werwer"))
	assert(mgr:getOrCreateMesh("qwe"))
	assert(mgr:getOrCreateModel("wer"))
	assert(mgr:getOrCreateRenderTarget("rt"))
	mgr:getOrLoadTexture2D("wer")
	mgr:getOrLoadModel("wer")
end, "ResourceManager")
