runTest(function()
	assert(solo.PolygonFace_All ~= nil)
	assert(solo.PolygonFace_CCW ~= nil)
	assert(solo.PolygonFace_CW ~= nil)

	assert(solo.AutoBinding_CameraWorldPosition ~= nil)
	assert(solo.AutoBinding_InverseTransposedWorldMatrix ~= nil)
	assert(solo.AutoBinding_InverseTransposedWorldViewMatrix ~= nil)
	assert(solo.AutoBinding_ProjectionMatrix ~= nil)
	assert(solo.AutoBinding_ViewMatrix ~= nil)
	assert(solo.AutoBinding_ViewProjectionMatrix ~= nil)
	assert(solo.AutoBinding_WorldMatrix ~= nil)
	assert(solo.AutoBinding_WorldViewMatrix ~= nil)
	assert(solo.AutoBinding_WorldViewProjectionMatrix ~= nil)
	assert(solo.AutoBinding_None ~= nil)

	local mgr = engine:getResourceManager()
	local e = mgr:getOrCreateEffect("vs", "fs")
	local m = mgr:getOrCreateMaterial(e, "test/uri")
	local mp = m:getParameter("param")
	assert(mp)
	assert(m:getEffect())

	m:setPolygonFace(solo.PolygonFace_All)
	assert(m:getPolygonFace() == solo.PolygonFace_All)

	local v2 = solo.Vector2.unit()
	local v3 = solo.Vector3.unit()
	local v4 = solo.Vector4.unit()
	local mat = solo.Matrix()
	local tex = mgr:getOrCreateTexture2D()

	mp:setFloat(1)
	mp:setFloatArray({1, 2, 3})
	mp:setInt(1)
	mp:setIntArray({1, 2, 3})
	mp:setVector2(v2)
	mp:setVector2Array({v2})
	mp:setVector3(v3)
	mp:setVector3Array({v3})
	mp:setVector4(v4)
	mp:setVector4Array({v4})
	mp:setMatrix(mat)
	mp:setMatrixArray({mat})
	mp:setTexture(tex)
	mp:setTextureArray({tex})
	mp:setFunction(function (var, renderContext) end)

	mp:bindValue(solo.AutoBinding_CameraWorldPosition)
	mp:bindValue(solo.AutoBinding_InverseTransposedWorldMatrix)
	mp:bindValue(solo.AutoBinding_InverseTransposedWorldViewMatrix)
	mp:bindValue(solo.AutoBinding_ProjectionMatrix)
	mp:bindValue(solo.AutoBinding_ViewMatrix)
	mp:bindValue(solo.AutoBinding_ViewProjectionMatrix)
	mp:bindValue(solo.AutoBinding_WorldMatrix)
	mp:bindValue(solo.AutoBinding_WorldViewMatrix)
	mp:bindValue(solo.AutoBinding_WorldViewProjectionMatrix)

end, "Material")
