runTest(function()
	local mgr = device:getResourceManager()
	local t = mgr:getOrCreateTexture2D()
	t:setData(solo.ColorFormat.RGB, {1, 2, 3, 4}, 2, 2)
	t:generateMipmaps()
	assert(t:getSize() ~= nil)
	assert(t:getVerticalWrapping() ~= nil)
	assert(t:getHorizontalWrapping() ~= nil)
	assert(t:getMinFiltering() ~= nil)
	assert(t:getMagFiltering() ~= nil)
	assert(t:getAnisotropyLevel() ~= nil)
	t:setVerticalWrapping(solo.TextureWrapping.Clamp)
	t:setHorizontalWrapping(solo.TextureWrapping.Clamp)
	t:setWrapping(solo.TextureWrapping.Clamp)
	t:setMinFiltering(solo.TextureFiltering.Linear)
	t:setMagFiltering(solo.TextureFiltering.Linear)
	t:setFiltering(solo.TextureFiltering.Linear)
	t:setAnisotropyLevel(1)
end, "Texture2D")
