runTest(function()
	local rt = device:getResourceManager():getOrCreateRenderTarget("test/uri")
	local tex = device:getResourceManager():getOrCreateTexture2D("nonesense")
	rt:setColorAttachment(0, tex)
	rt:setColorAttachment(2, tex)
	rt:setColorAttachment(1, tex)
	rt:getColorAttachmentCount()
	rt:getColorAttachment(0)
	rt:getColorAttachment(1)
	rt:getColorAttachment(2)
end, "RenderTarget")
